## **Import**

In [2]:
import pandas as pd

## **Load Dataset**

In [3]:
df = pd.read_csv("data/titanic.csv")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## **Simple Filtering**

In [4]:
df[df['age'] > 30]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## **Multi-Conditional Filtering**

In [5]:
df[(df['age'] > 30) & (df['sex'] == 'male')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
873,0,3,male,47.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
881,0,3,male,33.0,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
df[(df['age'] < 25) | (df['survived'] == 1)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

## **Boolean Masking**

In [7]:
mask = df['fare'] > 50
df[mask]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
856,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
867,0,1,male,31.0,0,0,50.4958,S,First,man,True,A,Southampton,no,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False

## **Query-Based Filtering**

In [8]:
df.query("age > 30 and sex == 'female'")

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
862,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
865,1,2,female,42.0,0,0,13.0000,S,Second,woman,False,NaN,Southampton,yes,True
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False

## **Column-Based Filtering**

In [9]:
df.loc[df['pclass'] == 1, ['age', 'fare', 'sex']]

      age     fare     sex
1    38.0  71.2833  female
3    35.0  53.1000  female
6    54.0  51.8625    male
11   58.0  26.5500  female
23   28.0  35.5000    male
..    ...      ...     ...
871  47.0  52.5542  female
872  33.0   5.0000    male
879  56.0  83.1583  female
887  19.0  30.0000  female
889  26.0  30.0000    male

[216 rows x 3 columns]

## **Complex Filtering**

In [10]:
df[
    (df['pclass'] == 1) &
    (df['fare'] > 100) &
    (df['survived'] == 1)
]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
31,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
88,1,1,female,23.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
195,1,1,female,58.00,0,0,146.5208,C,First,woman,False,B,Cherbourg,yes,True
215,1,1,female,31.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
258,1,1,female,35.00,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
268,1,1,female,58.00,0,1,153.4625,S,First,woman,False,C,Southampton,yes,False
269,1,1,female,35.00,0,0,135.6333,S,First,woman,False,C,Southampton,yes,True
299,1,1,female,50.00,0,1,247.5208,C,First,woman,False,B,Cherbourg,yes,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
306,1,1,female,NaN,0,0,110.8833,C,First,woman,False,NaN,Cherbourg,yes,True
307,1,1,female,17.00,1,0,108.9000,C,First,woman,False,C,Cherbourg,yes,False
311,1,1,female,18.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
318,1,1,female,31.00,0,2,164.8667,S,First,woman,False,C,Southampton,yes,False
319,1,1,female,40.00,1,1,134.5000,C,First,woman,False,E,Cherbourg,yes,False
325,1,1,female,36.00,0,0,135.6333,C,First,woman,False,C,Cherbourg,yes,True
334,1,1,female,NaN,1,0,133.6500,S,First,woman,False,NaN,Southampton,yes,False
337,1,1,female,41.00,0,0,134.5000,C,First,woman,False,E,Cherbourg,yes,True
341,1,1,female,24.00,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
380,1,1,female,42.00,0,0,227.5250,C,First,woman,False,NaN,Cherbourg,yes,True
390,1,1,male,36.00,1,2,120.0000,S,First,man,True,B,Southampton,yes,False
393,1,1,female,23.00,1,0,113.2750,C,First,woman,False,D,Cherbourg,yes,False
435,1,1,female,14.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
537,1,1,female,30.00,0,0,106.4250,C,First,woman,False,NaN,Cherbourg,yes,True
550,1,1,male,17.00,0,2,110.8833,C,First,man,True,C,Cherbourg,yes,False
581,1,1,female,39.00,1,1,110.8833,C,First,woman,False,C,Cherbourg,yes,False
609,1,1,female,40.00,0,0,153.4625,S,First,woman,False,C,Southampton,yes,True
660,1,1,male,50.00,2,0,133.6500,S,First,man,True,NaN,Southampton,yes,False
679,1,1,male,36.00,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
689,1,1,female,15.00,0,1,211.3375,S,First,child,False,B,Southampton,yes,False
700,1,1,female,18.00,1,0,227.5250,C,First,woman,False,C,Cherbourg,yes,False
708,1,1,female,22.00,0,0,151.5500,S,First,woman,False,NaN,Southampton,yes,True
716,1,1,female,38.00,0,0,227.5250,C,First,woman,False,C,Cherbourg,yes,True
730,1,1,female,29.00,0,0,211.3375,S,First,woman,False,B,Southampton,yes,True
737,1,1,male,35.00,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
742,1,1,female,21.00,2,2,262.3750,C,First,woman,False,B,Cherbourg,yes,False
763,1,1,female,36.00,1,2,120.0000,S,First,woman,False,B,Southampton,yes,False
779,1,1,female,43.00,0,1,211.3375,S,First,woman,False,B,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
856,1,1,female,45.00,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False

## **Using isin()**

In [11]:
df[df['embarked'].isin(['C', 'S'])]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

## **Save Filtered Output**

In [12]:
filtered_df = df[(df['age'] > 30) & (df['survived'] == 1)]
filtered_df.to_csv("data/filtered_output.csv", index=False)