## **Import**

In [1]:
import pandas as pd

## **Load Dataset**

In [2]:
file_path = "data/titanic.csv"
df = pd.read_csv(file_path)

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## **Basic Summary Stats**

In [3]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [4]:
df.describe(include='object')

C:\Users\M.Hanzlah Azam\AppData\Local\Temp\ipykernel_4952\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

                           Name   Sex  Ticket Cabin Embarked
count                       891   891     891   204      889
unique                      891     2     681   147        3
top     Braund, Mr. Owen Harris  male  347082    G6        S
freq                          1   577       7     4      644

## **Mean,Median,Std**

In [5]:
summary_stats = df.select_dtypes(include=['number']).agg(['mean', 'median', 'std'])
summary_stats

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
median,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429

## **Unique Values Per Column**

In [6]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

## **Value Counts**

In [7]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [8]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

## **Missing Values Report**

In [9]:
missing = df.isnull().sum()
missing

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [10]:
missing_percent = (missing / len(df)) * 100
missing_percent

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

## **Clean Summary Table**

In [11]:
summary_report = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values,
    "Missing Values": df.isnull().sum().values,
    "Missing %": ((df.isnull().sum() / len(df)) * 100).values,
    "Unique Values": df.nunique().values
})

summary_report

         Column Data Type  Missing Values  Missing %  Unique Values
0   PassengerId     int64               0   0.000000            891
1      Survived     int64               0   0.000000              2
2        Pclass     int64               0   0.000000              3
3          Name       str               0   0.000000            891
4           Sex       str               0   0.000000              2
5           Age   float64             177  19.865320             88
6         SibSp     int64               0   0.000000              7
7         Parch     int64               0   0.000000              7
8        Ticket       str               0   0.000000            681
9          Fare   float64               0   0.000000            248
10        Cabin       str             687  77.104377            147
11     Embarked       str               2   0.224467              3

In [12]:
summary_report.sort_values(by="Missing %", ascending=False)

         Column Data Type  Missing Values  Missing %  Unique Values
10        Cabin       str             687  77.104377            147
5           Age   float64             177  19.865320             88
11     Embarked       str               2   0.224467              3
0   PassengerId     int64               0   0.000000            891
3          Name       str               0   0.000000            891
2        Pclass     int64               0   0.000000              3
1      Survived     int64               0   0.000000              2
4           Sex       str               0   0.000000              2
7         Parch     int64               0   0.000000              7
6         SibSp     int64               0   0.000000              7
9          Fare   float64               0   0.000000            248
8        Ticket       str               0   0.000000            681